---
# Validation lab
# local users
fabric_name: MPLS_FABRIC

underlay_routing_protocol: isis
isis_advertise_passive_only: true
# Disabling ISIS hello padding makes it easier with vEOS-lab.
isis_hello_padding: false
isis_ti_lfa:
  enabled: true
  protection: link
  local_convergence_delay: 15000

label_distribution:
  # protocol: ldp
  protocol: isis-sr # Should be the default.

overlay_routing_protocol: ibgp
bgp_as: 65000
# If meshing PEs, client-to-client reflection can be turned off using rr bgp defaults.
# bgp_mesh_pes: true

# bgp peer groups passwords
bgp_peer_groups:
  MPLS_OVERLAY_PEERS:
    password: $1c$U4tL2vQP9QwZlxIV1K3/pw==

internal_vlan_order:
  allocation: ascending
  range:
    beginning: 3700
    ending: 3900

# Update p2p mtu
p2p_uplinks_mtu: 1600

# local_users:
#   someuser:
#     privilege: 15
#     role: network-admin
#     sha512_password: "someshapassword"

#   cvpadmin:
#     privilege: 15
#     role: network-admin
#     sha512_password: "someshapassword"

# Cloud Vision server information
cvp_instance_ip: 10.20.20.20
# This ingest key is set at CVP install time.
# cvp_ingestauth_key: somekey

# OOB Management network default gateway.
mgmt_gateway: 10.30.30.1

# dns servers.
name_servers:
  - 10.20.20.13
  - 8.8.8.8

# NTP Servers IP or DNS
# First NTP server will be preferred
# Sourced from Managment VRF
ntp_servers:
  - 0.se.pool.ntp.org
  - 1.se.pool.ntp.org

# Sets the administrative subfield of IP/MAC VRF Route-Distinguishers and Route-Targets
# These are actually the defaults. No need to set anything really.
overlay_rd_type:
  admin_subfield: overlay_loopback
overlay_rt_type:
  admin_subfield: 65000

# BGP max-paths and ecmp
bgp_maximum_paths: 4
bgp_ecmp: 4
# evpn_ebgp_multihop: 10

# EVPN prevent readvertising routes
overlay_prevent_readvertise_to_server: true

# Adjust default bfd values if desired.
bfd_multihop:
  interval: 5000
  min_rx: 5000
  multiplier: 3

custom_structured_configuration_sflow:
  sample: 40000
  vrfs:
    MGMT:
      destinations:
        "127.0.0.1":
      source_interface: Management1
  run: true

# Disable vlan aware bundles
vxlan_vlan_aware_bundles: false

# P Routers
p:
  platform: vEOS-LAB
  defaults:
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    # isis_system_id_prefix: '0000.0000'
    raw_eos_cli: |
      management security
         password encryption-key common
  nodes:
    p4:
      id: 4
      mgmt_ip: 10.30.30.104/24
      backbone_interfaces:
        - interface: Ethernet1
          uplink_switch: pe3
          uplink_switch_interface: Ethernet1
          ip_address: 100.64.0.0/31
          isis_metric: 80
          speed: 100g
          mtu: 1500
          isis_hello_padding: true
        - interface: Ethernet2
          uplink_switch: pe5
          uplink_switch_interface: Ethernet2
        - interface: Ethernet3
          uplink_switch: rr7
          uplink_switch_interface: Ethernet4
    p6:
      id: 6
      mgmt_ip: 10.30.30.106/24
      backbone_interfaces:
        - interface: Ethernet1
          uplink_switch: pe5
          uplink_switch_interface: Ethernet1
        - interface: Ethernet2
          uplink_switch: pe1
          uplink_switch_interface: Ethernet2

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

pe:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:00
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    # isis_system_id_prefix: '0000.0001'
    # loopback_ipv4_offset: 3
    backbone_interface_speed: forced 100gfull
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    # spanning_tree_root_super: true
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    mpls_route_reflectors: [ rr7, rr8 ]
    raw_eos_cli: |
      management security
         password encryption-key common
  node_groups:
    pe1-2:
      filter:
        tenants: [ TENANT_A ]
        tags: [ site1-2 ]
      nodes:
        pe1:
          id: 1
          mgmt_ip: 10.30.30.101/24
          backbone_interfaces:
            - interface: Ethernet1
              uplink_switch: pe2
              uplink_switch_interface: Ethernet1
            - interface: Ethernet2
              uplink_switch: p6
              uplink_switch_interface: Ethernet2
            - interface: Ethernet3
              uplink_switch: rr7
              uplink_switch_interface: Ethernet2
        pe2:
          id: 2
          mgmt_ip: 10.30.30.102/24
          backbone_interfaces:
            - interface: Ethernet1
              uplink_switch: pe1
              uplink_switch_interface: Ethernet1
            - interface: Ethernet2
              uplink_switch: pe3
              uplink_switch_interface: Ethernet2
            - interface: Ethernet3
              uplink_switch: rr8
              uplink_switch_interface: Ethernet1
              # id: 5
              # For auto p2p link addressing we could use the link id and get a /31 subnet from a supernet.
              # Then for IP calculation we could use the lowest node id to allocate the first address in the subnet.
    pe3:
      filter:
        tenants: [ TENANT_B ]
        tags: [ site3 ]
      nodes:
        pe3:
          id: 3
          mgmt_ip: 10.30.30.103/24
          backbone_interfaces:
            - interface: Ethernet1
              uplink_switch: p4
              uplink_switch_interface: Ethernet1
              ip_address: 100.64.0.1/31
              isis_metric: 80
              speed: 100g
              mtu: 1500
              isis_hello_padding: true
            - interface: Ethernet2
              uplink_switch: pe2
              uplink_switch_interface: Ethernet2
            - interface: Ethernet3
              uplink_switch: rr7
              uplink_switch_interface: Ethernet1
    pe5:
      filter:
        tenants: [ TENANT_A, TENANT_B ]
        tags: [ site5 ]
      nodes:
        pe5:
          id: 5
          mgmt_ip: 10.30.30.105/24
          backbone_interfaces:
            - interface: Ethernet1
              uplink_switch: p6
              uplink_switch_interface: Ethernet1
            - interface: Ethernet2
              uplink_switch: p4
              uplink_switch_interface: Ethernet2
            - interface: Ethernet3
              uplink_switch: rr7
              uplink_switch_interface: Ethernet3

rr:
  defaults:
    platform: vEOS-LAB
    loopback_ipv4_pool: 100.70.0.0/24
    loopback_ipv6_pool: "2000:1234:ffff:ffff::/64"
    # isis_system_id_prefix: '0000.0002'
    bgp_defaults:
      - 'no bgp default ipv4-unicast'
      - 'distance bgp 20 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
      - 'bgp route-reflector preserve-attributes always'
      # - 'no bgp client-to-client reflection' # If meshing PEs, client-to-client reflection can be turned off
    raw_eos_cli: |
      management security
         password encryption-key common
  node_groups:
    rr7-8:
      bgp_cluster_id: 7.7.7.7
      nodes:
        rr7:
          id: 7
          mgmt_ip: 10.30.30.107/24
          backbone_interfaces:
            - interface: Ethernet1
              uplink_switch: pe3
              uplink_switch_interface: Ethernet3
            - interface: Ethernet2
              uplink_switch: pe1
              uplink_switch_interface: Ethernet3
            - interface: Ethernet3
              uplink_switch: pe5
              uplink_switch_interface: Ethernet3
            - interface: Ethernet4
              uplink_switch: p4
              uplink_switch_interface: Ethernet3
            - interface: Ethernet5
              uplink_switch: rr8
              uplink_switch_interface: Ethernet2
        rr8:
          id: 8
          mgmt_ip: 10.30.30.108/24
          backbone_interfaces:
            - interface: Ethernet1
              uplink_switch: pe2
              uplink_switch_interface: Ethernet3
            - interface: Ethernet2
              uplink_switch: rr7
              uplink_switch_interface: Ethernet5

connected_endpoints_keys:
  routers:
    type: router
  cpes:
    type: cpe