---
tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  CUSTOMER1:
    vrfs:
      # VRF definitions inside the tenant.
      C1_VRF1:
        # VRF ID definition.
        vrf_id: 10
        address_families:
          - vpn-ipv4
        ospf:
          enabled: true
          nodes:
            - pe1
            - pe2
            - pe3
        l3_interfaces:
          # L3 interfaces
          - interfaces: [ Ethernet3.10, Ethernet4.10, Ethernet2 ]
            nodes: [ pe1, pe2, pe3 ]
            description: C1_VLAN10
            enabled: true
            ip_addresses: [ 10.0.1.1/29, 10.0.1.2/29, 10.0.1.9/30 ]
            ospf:
              enabled: true

  CUSTOMER2:
    vrfs:
      C2_VRF1:
        vrf_id: 20
        address_families:
          - vpn-ipv4
        l3_interfaces:
          # L3 interfaces
          - interfaces: [ Ethernet3.20, Ethernet4.20, Ethernet4 ]
            nodes: [ pe1, pe2, pe3 ]
            description: C2_VLAN20
            enabled: true
            ip_addresses: [ 10.1.1.1/29, 10.1.1.2/29, 10.1.1.9/30 ]
        bgp_peers:
          10.1.1.3:
            remote_as: 123
            description: C1_ROUTER1
            send_community: standard
            maximum_routes: 100
            nodes: [ pe1, pe2 ]
          # 10.1.1.3:
          #   remote_as: 123
          #   description: C1_ROUTER1
          #   send_community: standard
          #   maximum_routes: 100
          #   nodes: [ pe2 ]
          10.1.1.10:
            remote_as: 321
            description: C1_CPE
            send_community: standard
            maximum_routes: 100
            nodes: [ pe3 ]

