---
- name: Build Switch configuration
  hosts: MPLS_FABRIC
  connection: local
  gather_facts: false

  tasks:
    - name: generate intended variables
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      import_role:
        name: arista.avd.eos_cli_config_gen
