---
- name: Build EVPN configuration
  hosts: MPLS_EVPN
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:

    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs
      vars:
        design:
          type: "mpls"

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen

- name: Build IPVPN configuration
  hosts: IPVPN
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:
    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs
      vars:
        design:
          type: "mpls"

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen
