---
- name: Build Switch configuration
  hosts: MPLS_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:

    - name: generate intended variables
      import_role:
        name: arista.avd.eos_designs
      vars:
        design:
          type: "mpls-vpn"

    - name: generate device intended config and documentation
      import_role:
        name: arista.avd.eos_cli_config_gen

    - name: deploy configuration to device
      tags: [deploy, never]
      import_role:
         name: arista.avd.eos_config_deploy_eapi
